### ISSUE TITLE
image file is truncated

### ISSUE THREAD

**Issue by yuxijin** [tyui592/AdaIN_Pytorch#1]
Hi, I am running your code of AdaIN_Pytorch recently. But I always got the error about the image file truncated.  I have no idea of solving this issue. Could you please help me by giving me some advice or recommended solutions? Many thanks for your kind help.
![image](https://user-images.githubusercontent.com/43038911/105684739-512e7480-5f30-11eb-9462-c75a42934455.png)

**Comment by tyui592** [comment]
Hello, I think it is one of the following reasons.
- There is a corrupted image file or not an image file in the following directory, https://github.com/tyui592/AdaIN_Pytorch/blob/1ea8274f6d62b0b1cdedf73d0735088ffe6be987/utils.py#L61

If the problem is resolved, please close this issue.

**Comment by yuxijin** [comment]
I just checked all image files in the directory and founded some image files corrupted. Thank you very much~
